server:
  servlet:
    context-path: /app

app:
  datasource:
    east:
      url: jdbc:postgresql://localhost:54320/east
      username: postgres
      password: east
      hikari:
        max-connections: 10
    west:
      url: jdbc:postgresql://localhost:54321/west
      username: postgres
      password: west
