management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
        - health
        - env
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
      group:
        readiness:
          include: readinessState, kafka

spring:
  output:
    ansi:
      enabled: always
