services:
  east:
    image: postgres:14.8
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: east
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "east"

  west:
    image: postgres:14.8
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: west
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "west"
