server:
  servlet:
    context-path: /app

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
      group:
        readiness:
          #          include: readinessState, db
          include: readinessState, multiDataSource
  health:
    db:
      #      ignoreRoutingDataSources: true
      enabled: false


app:
  datasource:
    east:
      url: jdbc:postgresql://localhost:54320/east
      username: postgres
      password: east
      hikari:
        pool-name: east
        maximum-pool-size: 5
    west:
      url: jdbc:postgresql://localhost:54321/west
      username: postgres
      password: west
      hikari:
        pool-name: west
        maximum-pool-size: 5

spring:
  threads:
    virtual:
      enabled: true
  task:
    execution:
      simple:
        concurrency-limit: 100

decorator:
  datasource:
    ignore-routing-data-sources: true
    datasource-proxy:
      slow-query:
        threshold: 30s
